global:
  scrape_interval:     5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: 'kafka-prometheus-connector'
    static_configs:
      - targets: ['kafka-prometheus-connector:8080']